title: Hello, world! I'm Ines Gahlouzi
description: this is a blog that I've decided to create it to share my journey in the data science filed and to share my tutorials and my articals in the tech> # this means to ignore newlines until "baseurl:"
  
permalink: ':title/'
baseurl: "/Ines-s-Blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ines Gahlouzi # add your name
author-img: linkedprofile.jpeg # add your photo
about-author: I am a data science student seeking new challenges. Always hungry to keep learning. # add description
social-github: inesgh1 # add your Github handle
social-linkedin: https://www.linkedin.com/in/ines-gahlouzi/ # add your Linkedin handle
social-email: inesgahlouzi11@gmail.com# add your Email address

# Disqus
discus-identifier: ms_genuis # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
